package com.example.demo1.logindemo.model;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    private Integer id;


    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.name
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.content
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.status
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCid() {
        return cid;
    }

    public void setCid(Integer cid) {
        this.cid = cid;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.name
     *
     * @return the value of article.name
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.name
     *
     * @param name the value for article.name
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.content
     *
     * @return the value of article.content
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.content
     *
     * @param content the value for article.content
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.status
     *
     * @return the value of article.status
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.status
     *
     * @param status the value for article.status
     *
     * @mbggenerated Tue Aug 25 11:45:06 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}