package com.example.demo1.logindemo.model;

public class ArticleType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.id
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.name
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.content
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.status
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.id
     *
     * @return the value of article_type.id
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.id
     *
     * @param id the value for article_type.id
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.name
     *
     * @return the value of article_type.name
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.name
     *
     * @param name the value for article_type.name
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.content
     *
     * @return the value of article_type.content
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.content
     *
     * @param content the value for article_type.content
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.status
     *
     * @return the value of article_type.status
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.status
     *
     * @param status the value for article_type.status
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}