package com.example.demo1.logindemo.model;

public class DeliveryAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.id
     *
     * @mbggenerated Tue Aug 25 11:24:08 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.cid
     *
     * @mbggenerated Tue Aug 25 11:24:08 CST 2020
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_address.name
     *
     * @mbggenerated Tue Aug 25 11:24:08 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.id
     *
     * @return the value of delivery_address.id
     *
     * @mbggenerated Tue Aug 25 11:24:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.id
     *
     * @param id the value for delivery_address.id
     *
     * @mbggenerated Tue Aug 25 11:24:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.cid
     *
     * @return the value of delivery_address.cid
     *
     * @mbggenerated Tue Aug 25 11:24:08 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.cid
     *
     * @param cid the value for delivery_address.cid
     *
     * @mbggenerated Tue Aug 25 11:24:08 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_address.name
     *
     * @return the value of delivery_address.name
     *
     * @mbggenerated Tue Aug 25 11:24:08 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_address.name
     *
     * @param name the value for delivery_address.name
     *
     * @mbggenerated Tue Aug 25 11:24:08 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}