server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
logging:
  pattern:
    file: G:\demo2\logs\logs.log
    level: debug


mybatis:
  mapper-locations:
    - classpath:/mapper/*.xml






