package com.example.demo1.logindemo.dao;

import com.example.demo1.logindemo.model.ArticleType;
import com.example.demo1.logindemo.model.ArticleTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    int countByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    int deleteByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    int insert(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    int insertSelective(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    List<ArticleType> selectByExample(ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    ArticleType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") ArticleType record, @Param("example") ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    int updateByExample(@Param("record") ArticleType record, @Param("example") ArticleTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    int updateByPrimaryKeySelective(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbggenerated Fri Sep 04 15:31:26 CST 2020
     */
    int updateByPrimaryKey(ArticleType record);
}